language: python

python:
  - 2.7
  - 3.3
  - 3.4
  - 3.5

env:
  - DJANGO_VERSION=1.6
  - DJANGO_VERSION=1.7
  - DJANGO_VERSION=1.8
  - DJANGO_VERSION=1.9
  - DJANGO_VERSION=dev

matrix:
  exclude:
    - python: 3.4
      env: DJANGO_VERSION=1.6
    - python: 3.5
      env: DJANGO_VERSION=1.6
    - python: 3.5
      env: DJANGO_VERSION=1.7
    - python: 3.5
      env: DJANGO_VERSION=1.7
    - python: 3.3
      env: DJANGO_VERSION=1.9
    - python: 3.3
      env: DJANGO_VERSION=dev
  allow_failures:
    - python: 3.5
      env: DJANGO_VERSION=dev
    - python: 3.4
      env: DJANGO_VERSION=dev
    - python: 3.3
      env: DJANGO_VERSION=dev
    - python: 2.7
      env: DJANGO_VERSION=dev

install:

 - if [[ $DJANGO_VERSION == dev ]]; then pip
   install https://github.com/django/django/tarball/master/django.tar.gz#egg=django; else pip
   install -q Django==$DJANGO_VERSION; fi

 - pip install -r requirements-test.txt

 - python setup.py develop

before_script:
 - flake8 --ignore=E501 admin_top_models

script:
 - python runtests.py

after_success:
 - coverage run runtests.py
 - pip install coveralls
 - coveralls